### ISSUE TITLE
Met some memory limit of MongoDB

### ISSUE THREAD

**Issue by gtoffoli** [up2university/learninglocker2-docker#11]
Recently I got many times the error message "Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit.", while using the Query Builder, more precisely when trying to create interactively a clause OR-ing many object ids. Said message is emitted by LL when constructing an option list with items representing automatic continuations of the user input. See also: https://stackoverflow.com/questions/54396869/mongo-exec-error-operationfailed-sort-operation-used-more-than-the-maximum-3

I don't know if someone can change the LL configuration appropriately. However, the suggestion "or specify a smaller limit" confuses me a bit.

**Comment by michzimny** [comment]
We could adjust the configuration but we would need to investiage it deeper to be sure what should be changed.

We could also create indexes that are [recommended by the LL documentation](http://docs.learninglocker.net/guides-indexing/) that we do not have in our instances.

See also #10. Perhaps, we should first upgrade the LL app to 3.x and also upgrade the underlying Mongo db (LL v.3.x requires a newer version of Mongo than we currently have) in order not to fight this issue more than once.

@gtoffoli, any suggestions are welcomed.

**Comment by gtoffoli** [comment]
Thank you Michal: I think it's quite likely that creating the indexes recommended by the documentation would solve the problem.

By the way, I met a similar problem in querying LL through the HTTP API; but in that case the cause is the limited length of the query-string encoding the MongoDB query in a GET request. The problem can only be circumvented by redesigning the algorithm.

**Comment by michzimny** [comment]
@gtoffoli, so I just created the indexes suggested by the docs, for both Up2U instances. Could you please check if it solves the issue?

**Comment by michzimny** [comment]
@gtoffoli, have you experienced similar problems after my changes?

**Comment by gtoffoli** [comment]
Yes, I've experienced similar problems, but much less frequently. Thank you. I think that you can close this issue for now.
