### ISSUE TITLE
LL upgrade

### ISSUE THREAD

**Issue by michzimny** [up2university/learninglocker2-docker#3]
@gtoffoli, we're currently using v2.0.5 of LL, so it's a year old. Shall we upgrade to a more recent one and try to see if the user experience is better then?

**Comment by gtoffoli** [comment]
@michzimny, If you refer to the issue I mentioned in my mail, it doesn't concern LL, but what is upstream, i.e. the moodle_logstore-xAPI extension and/or the SSO implementation.

Really, I don't know how much the new version of LL is better. I'm just starting to learn how to use its analytics dashboard.
I can only mention a couple of annoying things in defining a visualization:
- when adding a query to a series, I cannot find a way to clone and then modify an existing query
- in the right pane, when one chooses a new value for the X axis (say changes the interval in the time axis), all queries in the defined series are visualized (the current state of the toggles is lost).

**Comment by michzimny** [comment]
So my suggestion is to upgrade it and see it's better then with those user experience issues. I will try to manage this.

**Comment by gtoffoli** [comment]
@michzimny, I agree, thanks. In fact it seems that recent versions of the Dashboard include many usability improvements.

**Comment by gytisc** [comment]
We definitely need to upgrade - we see a lot of malfunctioning in this old version (almost half of the statements from Lithuanian Moodle is failing, persons of already submitted statement does not appear in the list, etc.)  and tracing logs to report bugs makes sense only if we have most current version.

**Comment by michzimny** [comment]
Ok, we will schedule an upgrade.
