### ISSUE TITLE
Accessing the Aggregation HTTP interface

### ISSUE THREAD

**Issue by gtoffoli** [up2university/learninglocker2-docker#4]
With the remote idea of recurring to the HTTP Aggregation API, in order to overcome some limitations of the LL Dashboard, I wanted to test the possibility of calling it from a Jupyter notebook. Then, I've tried to send a request to the url https://lrs.test.up2university.eu/api/statements/aggregate , following the simplest example in http://docs.learninglocker.net/http-aggregation/

Since I was getting a 400 HTTP response (_bad request_), in my request I've tried to change the port to 8080 (example value from the LL Configuration guide): I got a _timeout error_ after that the Python kernel of Jupyter was busy for a few minutes.

Reverting to the 80 port, I repeatedly got from the Python library urllib3 an _SSLError_ (SSL: UNKNOWN_PROTOCOL).
Now I get again a quick response (400 - bad request) only using the _http_ protocol in place of _https_.

Does somebody know what it the correct endpoint to use, including protocol and port?
Should I ask Nadav?
Thanks.

**Comment by michzimny** [comment]
I do not know the API but the response body says to me "Unauthorized". What does say your response body when requesting the endpoint? Perhaps, you're providing wrong authorization information or you can see another message explaining the error.

**Comment by gtoffoli** [comment]
Thank you Michal.
Now I gave the required authentication to the LL client and fixed an error in building the request.
Found no more problems in calling the simpler HTTP REST API, both from Jupyter and from a plain Python console.
Will try again the Aggregation API, whose use seems much more complex: it assumes the knowledge of the Mongo query API.
